FROM node:20-alpine AS build
WORKDIR /app

ARG REACT_APP_GEMINI_API_KEY
ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ARG REACT_APP_FIREBASE_APP_ID

ENV REACT_APP_GEMINI_API_KEY=AIzaSyDbH5CzOWA4TJJIOPT2odl0kEn7wVAvbU4
ENV REACT_APP_FIREBASE_API_KEY=AIzaSyAstloJQFDsWm4jcDSjAJF_z1w1gCzYlCU
ENV REACT_APP_FIREBASE_AUTH_DOMAIN=fairforce-47446.firebaseapp.com
ENV REACT_APP_FIREBASE_PROJECT_ID=fairforce-47446
ENV REACT_APP_FIREBASE_STORAGE_BUCKET=fairforce-47446.firebasestorage.app
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID=664021461997
ENV REACT_APP_FIREBASE_APP_ID=664021461997

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
